// /constants/foundational.constants.ts

import { FoundationalFormValues } from "@/schemas/foundational.schemas";




// ---------------------------
// Select options for dropdowns
// ---------------------------



export const LEGAL_FORMS = [
  { value: "PRIVATE_LIMITED", label: "Private limited liability" },
  { value: "SOLE_PROPRIETORSHIP", label: "Sole proprietorship" },
  { value: "PARTNERSHIP", label: "Partnership" },
  { value: "COOPERATIVE", label: "Cooperative" },
  { value: "LLC", label: "Limited Liability Company (LLC)" },
  { value: "PLC", label: "Public Limited Company (PLC)" },
  { value: "SA", label: "Société Anonyme (SA)" },
  { value: "GMBH", label: "Gesellschaft mit beschränkter Haftung (GmbH)" },
  { value: "SAS", label: "Société par actions simplifiée (SAS)" },
  { value: "OTHER", label: "Other (specify)" },
] as const;

export const OWNERSHIP_NATURE = [
  { value: "FOUNDER_OWNED", label: "Founder-owned" },
  { value: "FAMILY_OWNED", label: "Family-owned" },
  { value: "EMPLOYEE_OWNED", label: "Employee-owned / ESOP" },
  { value: "COOP_MEMBER", label: "Cooperative (member-owned)" },
  { value: "VC_PE_CONTROLLED", label: "VC/PE-controlled" },
  { value: "STATE_MUNICIPAL", label: "State-owned / Municipal" },
  { value: "FOUNDATION_NGO", label: "Foundation / NGO-owned" },
  { value: "PUBLICLY_LISTED", label: "Publicly listed" },
  { value: "PRIVATE", label: "Private" },
  { value: "STATE", label: "State-owned" },
  { value: "COOPERATIVE", label: "Cooperative" },
  { value: "NONPROFIT_ASSOC", label: "Non-profit / Association" },
  { value: "WIDELY_HELD_PRIVATE", label: "Widely held (private)" },
  { value: "OTHER", label: "Other (specify)" },
] as const;

export const SME_CLASSES = [
  { value: "MICRO", label: "Micro" },
  { value: "SMALL", label: "Small" },
  { value: "MEDIUM", label: "Medium" },
] as const;

export const NACE_SECTORS = [
  { value: "A", label: "A - Agriculture, forestry and fishing" },
  { value: "B", label: "B - Mining and quarrying" },
  { value: "C", label: "C - Manufacturing" },
  { value: "D", label: "D - Electricity, gas, steam and air conditioning supply" },
  { value: "E", label: "E - Water supply; sewerage, waste management" },
  { value: "F", label: "F - Construction" },
  { value: "G", label: "G - Wholesale and retail trade" },
  { value: "H", label: "H - Transportation and storage" },
  { value: "I", label: "I - Accommodation and food service activities" },
  { value: "J", label: "J - Information and communication" },
  { value: "K", label: "K - Financial and insurance activities" },
  { value: "L", label: "L - Real estate activities" },
  { value: "M", label: "M - Professional, scientific and technical activities" },
  { value: "N", label: "N - Administrative and support service activities" },
  { value: "O", label: "O - Public administration and defence" },
  { value: "P", label: "P - Education" },
  { value: "Q", label: "Q - Human health and social work activities" },
  { value: "R", label: "R - Arts, entertainment and recreation" },
  { value: "S", label: "S - Other service activities" },
  { value: "T", label: "T - Household activities" },
  { value: "U", label: "U - Extraterritorial organisations and bodies" },
] as const;

export const VALUE_CHAIN_SCOPES = [
  { value: "CORE_OPERATIONS", label: "Core operations" },
  { value: "UPSTREAM", label: "Upstream" },
  { value: "DOWNSTREAM", label: "Downstream" },
  { value: "SERVICES", label: "Services" },
  { value: "OTHER", label: "Other" },
] as const;

export const RESTATEMENT_REASONS = [
  { value: "METHODOLOGY_CHANGE", label: "Methodology change" },
  { value: "BASE_PERIOD_CHANGE", label: "Base period change" },
  { value: "MERGER_ACQUISITION", label: "Merger / Acquisition" },
  { value: "ERROR_CORRECTION", label: "Error correction" },
  { value: "OTHER", label: "Other" },
] as const;

export const FREQUENCY_OPTIONS = [
  { value: "ANNUAL", label: "Annual" },
  { value: "BIENNIAL", label: "Biennial" },
  { value: "AD_HOC", label: "Ad-hoc" },
] as const;

export const ALIGNMENT_FLAGS = [
  { value: "ILO_PRINCIPLES", label: "ILO Principles" },
  { value: "LOCAL_LAWS", label: "Local laws" },
] as const;

export const SDG_OPTIONS = [
  { value: "SDG1", label: "No Poverty" },
  { value: "SDG2", label: "Zero Hunger" },
  { value: "SDG3", label: "Good Health and Well-being" },
  { value: "SDG4", label: "Quality Education" },
  { value: "SDG5", label: "Gender Equality" },
  { value: "SDG6", label: "Clean Water and Sanitation" },
  { value: "SDG7", label: "Affordable and Clean Energy" },
  { value: "SDG8", label: "Decent Work and Economic Growth" },
  { value: "SDG9", label: "Industry, Innovation and Infrastructure" },
  { value: "SDG10", label: "Reduced Inequalities" },
  { value: "SDG11", label: "Sustainable Cities and Communities" },
  { value: "SDG12", label: "Responsible Consumption and Production" },
  { value: "SDG13", label: "Climate Action" },
  { value: "SDG14", label: "Life Below Water" },
  { value: "SDG15", label: "Life on Land" },
  { value: "SDG16", label: "Peace, Justice and Strong Institutions" },
  { value: "SDG17", label: "Partnerships for the Goals" },
] as const;

// Expanded currency list per request
export const CURRENCIES = [
  { value: "USD", label: "USD - US Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Złoty" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "TWD", label: "TWD - Taiwan Dollar" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "ILS", label: "ILS - Israeli Shekel" },
] as const;

export const COUNTRIES = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AO", label: "Angola" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "BD", label: "Bangladesh" },
  { value: "BE", label: "Belgium" },
  { value: "BJ", label: "Benin" },
  { value: "BR", label: "Brazil" },
  { value: "BW", label: "Botswana" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "CD", label: "Congo (DRC)" },
  { value: "CI", label: "Côte d’Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "EG", label: "Egypt" },
  { value: "ET", label: "Ethiopia" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "HU", label: "Hungary" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KE", label: "Kenya" },
  { value: "KR", label: "Korea (South)" },
  { value: "KW", label: "Kuwait" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "ML", label: "Mali" },
  { value: "MX", label: "Mexico" },
  { value: "MZ", label: "Mozambique" },
  { value: "NA", label: "Namibia" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NG", label: "Nigeria" },
  { value: "NO", label: "Norway" },
  { value: "PK", label: "Pakistan" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SG", label: "Singapore" },
  { value: "ZA", label: "South Africa" },
  { value: "ES", label: "Spain" },
  { value: "SD", label: "Sudan" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TR", label: "Turkey" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "VN", label: "Vietnam" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
] as const;


// ---------------------------
// Default values for the form
// ---------------------------

export const DEFAULT_FOUNDATIONAL_VALUES = {
  companyBasics: {
    legalForm: undefined,
    ownershipNature: undefined,
    isPublic: undefined,
    reportingCurrency: undefined,
    smeClass: undefined,
    naceCode: undefined,
    employeeCount: "",
    companyActivities: "",
  },
  identifiers: { lei: "", duns: "", euId: "", permId: "" },
  headquarters: {
    hqCountry: undefined,
    hqRegion: "",
    hqCity: "",
    hqAddress: "",
    hqLatitude: undefined,
    hqLongitude: undefined,
  },
  registeredOffice: {
    registeredCountry: undefined,
    registeredRegion: "",
    registeredCity: "",
    registeredAddress: "",
    registeredZip: "",
  },
  financials: { annualTurnover: undefined, balanceSheetTotal: undefined },
  valueChain: { valueChainScopes: [], businessRelations: [] },
  supplyChain: { isInMNCChain: undefined, parentName: "", parentLocation: "", parentUrl: "" },
  alignments: {
    sdgCodes: [],
    alignmentFlags: [],
    alignmentDetails: "",
    activitiesSummary: "",
    strategySummary: "",
    operatingContext: "",
    stakeholderSummary: "",
  },
  disclosurePeriods: {
    sustainabilityPeriodStart: undefined,
    sustainabilityPeriodEnd: undefined,
    financialPeriodStart: undefined,
    financialPeriodEnd: undefined,
    periodDifferenceReason: "",
    dateOfInformation: undefined,
    frequency: undefined,
  },
  disclosureContact: { contactName: "", contactEmail: "" },
  firstRestatement: {
    isFirstReport: undefined,
    isRestated: undefined,
    restatementReasons: [],
    restatementNotes: "",
  },
  sustainabilityGovernance: {
    hasSustainabilityCert: undefined,
    certification: { issuer: "", issuingDate: undefined, file: undefined },
    draftedPractices: undefined,
    arePubliclyAvailable: undefined,
    haveTargets: undefined,
    accountableJobTitle: "",
    policies: {}, // start empty; rows render safely
    hasExternalAudit: undefined,
  },
  documents: { registrationCertFile: undefined, previousReportFiles: [] },
} as const;

export const createFoundationalDefaults = (): FoundationalFormValues =>
  structuredClone(DEFAULT_FOUNDATIONAL_VALUES) as unknown as FoundationalFormValues;

